### ISSUE TITLE
Improve Trivia

### ISSUE THREAD

**Issue by Bakaba** [Kwoth/NadekoBot#180]
Hello,

I think Trivia can be improved by adding more questions with other topic (like anime, Nadekobot, and more stuff about other countries but U.S. - Because I'm not living in U.S. and I don't know how was going there), or possibility to choose a subject, like ">t anime", who will display questions related to anime only (perhaps add subject tags to questions for that, or something).

Thanks for reading this and keep your good work, Kwoth and contributors to Nadekobot ! <3

**Comment by Kwoth** [comment]
Can you provide some question resources?

**Comment by Bakaba** [comment]
By resources, you mean a question database somewhere in the web, or if I can create a pack of questions and send it to you ?

**Comment by Kwoth** [comment]
@Bakaba https://raw.githubusercontent.com/Kwoth/NadekoBot/master/NadekoBot/bin/Debug/data/questions.json

New questions should all have a Category too, like some of the questions have atm

**Comment by Bakaba** [comment]
Thanks ! =)
I've noticed that some question have no category, or have the beginning of the question in the category (Like this : http://puu.sh/oe822/2dfd582227.png). You don't mind if I fix this too, right ?

**Comment by Kwoth** [comment]
Cool, thanks

**Comment by Kwoth** [comment]
Did you give up on this? I see last update was 4 days ago @Bakaba

**Comment by Bakaba** [comment]
No, I did edit offline, and I forgot to update it. x) Since I'm doing it alone, I'll take some time to complete it, but I'll do it for sure. x)

**Comment by Bakaba** [comment]
Hm, I'll be difficult for me to doing it now, since I have exams, so I'll let this on stand-by and focus on my studies. I'll do it once I finish all my personal stuff. If someone else can help, or if you want to wait until July, it's up to you. I'll merge what I have done for now.

**Comment by Kwoth** [comment]
This should be resolved within a week.

**Comment by triccetti** [comment]
Hey I made my own questions.json file with a bunch of World of Warcraft related trivia. I am trying to replace the original questions file with this one. I copied your same exact format however when I try to use my file the bot doesn't pull the questions up for some reason. When I replace it with the original the original works again. Not sure why it's not working. I'll attach the file here.

It wouldn't let me upload a JSON so I uploaded a .txt file.

[questions.txt](https://github.com/Kwoth/NadekoBot/files/311024/questions.txt)

**Comment by Kwoth** [comment]
try removing the comma at the end @triccetti

**Comment by triccetti** [comment]
@Kwoth Nope that did not fix it. I also tried removing all the other possible options of commas in the file and it still doesn't work. The only thing that happens is when I type >t Nadekobot says "Trivia game started! 10 points needed to win." followed by no question. We have even tried waiting a long period of time to see if anything happens.

**Comment by triccetti** [comment]
Bump

**Comment by Kwoth** [comment]
You screwed up your json somehow, i can't help you. Don't bump unrelated issues. Make sure it's in the correct format and it will work.

**Comment by VorgunTheBeta** [comment]
I've got a question, is it possible to make it so you can start the trivia with a certain category?

**Comment by xnaas** [comment]
@VorgunTheBeta trivia is not currently broken down into categories. Although, I think that wouldn't be a bad idea. Often times my server will get 5-8 questions in a row about topics none of us have any knowledge about.

**Comment by VorgunTheBeta** [comment]
@xnaas I have the same thing sometimes, and that way, it would be better, for say an anime server to have only anime questions etc without having to mess with the code without know how it works.

**Comment by eurotransient** [comment]
I've been playing around with a hosted version of NadekoBot and am hoping to put some work into the trivia, since it's a feature I've been looking for.

One thing I did manage to do was grab an insanely massive archive of Jeopardy questions (150k or so) and format them in a way NadekoBot can read without any issues. (I'd upload here but it's 33mb)

The only problem is a lot of times jeopardy questions depend on knowing the category, so having a way to display that with the question would improve the experience a lot. I've got category data in the original scrape I found, too.

I also have question value data, as well, which might be useful to provide variable points for harder questions in trivia.

Anyways, I'm not really a programmer and don't really know how to work in Git, but if the questions file I put together would be useful, I'm happy to get it delivered.

**Comment by Kwoth** [comment]
yes sure, just upload it to mega or something and post the link here @eurotransient , thanks. 

Trivia will be rewritten in 1.0 (coming soon :tm: )

**Comment by eurotransient** [comment]
Here you go!

https://mega.nz/#!gUpCADaI!OweHEiBnMwA-Cp9-ptyPoik9E1ZvXMYCih_E0KTx04M

I included both a version with just questions and answers, as well as one that includes categories and values. Hope it helps, looking forward to 1.0!
