### ISSUE TITLE
Cant start?

### ISSUE THREAD

**Issue by GethelpObv** [Kwoth/NadekoBot#905]
i Followed the windows guide tried reinstalling 10+ times i am on windows 10 i look at all the issues and did not find anything on this

https://i.gyazo.com/b835cc29b0b738b3fad45e3d54a17388.png

any help would be grate

**Comment by samdivaio** [comment]
looks like you are running batch files from a different place, unsure, but do this:
1. Make a "Nadeko" folder on desktop and but just the NadekoInstaller.bat
2. Run and install latest build.
3. Put back your credential.json
4. Use the same bat file to run it, don't move any files to anywhere.
It should fix it, if not them mention @samvaio here https://discord.gg/Jpux9

**Comment by GethelpObv** [comment]
https://i.gyazo.com/4cd75e725a48ad5d44bd9bd7b59ed848.png

tried that  didnt work still get the same thing

**Comment by ttshivers** [comment]
I am having the same issue with the program reporting that the lock file is missing

**Comment by Kwoth** [comment]
try doing this ttshivers

cd NadekoBot/src/NadekoBot
dotnet restore
dotnet run --configuration Release

**Comment by ttshivers** [comment]
Unfortunately, this did not fix my problem. Here is the output from running those commands:
`:~/NadekoBot/src/NadekoBo$ dotnet restore
log  : Restoring packages for /home/user/NadekoBot/src/NadekoBot/project.json...
log  : Restoring packages for tool 'Microsoft.EntityFrameworkCore.Tools.DotNet' in /home/user/NadekoBot/src/NadekoBot/project.json...
log  : Restoring packages for tool 'Microsoft.DotNet.Watcher.Tools' in /home/user/NadekoBot/src/NadekoBot/project.json...
log  : Lock file has not changed. Skipping lock file write. Path: /home/user/NadekoBot/src/NadekoBot/project.lock.json
log  : /home/user/NadekoBot/src/NadekoBot/project.json
log  : Restore completed in 2519ms.
:~/NadekoBot/src/NadekoBot$ dotnet run --configuration Release
Project Discord.Net does not have a lock file. Please run "dotnet restore" to generate a new lock file.
Project Discord.Net does not have a lock file. Please run "dotnet restore" to generate a new lock file.
`

**Comment by Kwoth** [comment]
delete everything, make sure you've downloaded the correct installer, close all folders and just run the installer. Wait for it to say installation is completed.

It seems your submodule wasn't downloaded, which could happen if you accidentaly closed installer prematurely or thought installation is complete.

**Comment by ttshivers** [comment]
Deleting everything and starting over did result in the bot working for me. Thank you for helping me out

**Comment by Kwoth** [comment]
Glad to hear that, enjoy ^^

**Comment by monkunzero4** [comment]
C:\Windows\system32>D:

D:\>cd NadekoBot

D:\NadekoBot>cd Nadeko

D:\NadekoBot\Nadeko>cd src

D:\NadekoBot\Nadeko\src>cd NadekoBot

D:\NadekoBot\Nadeko\src\NadekoBot>dotnet restore
log  : Restoring packages for D:\NadekoBot\Nadeko\src\NadekoBot\project.json...
error: Unable to resolve 'Discord.Net.Commands (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.
error: Unable to resolve 'Discord.Net.WebSocket (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.
log  : Restoring packages for tool 'Microsoft.EntityFrameworkCore.Tools.DotNet' in D:\NadekoBot\Nadeko\src\NadekoBot\project.json...
log  : Installing NuGet.Configuration 3.5.0-beta2-1484.
log  : Installing NuGet.Protocol.Core.Types 3.5.0-beta2-1484.
log  : Installing NuGet.Protocol.Core.v3 3.5.0-beta2-1484.
log  : Installing NuGet.Repositories 3.5.0-beta2-1484.
log  : Installing NuGet.LibraryModel 3.5.0-beta2-1484.
log  : Installing NuGet.Packaging.Core.Types 3.5.0-beta2-1484.
log  : Installing Microsoft.DotNet.InternalAbstractions 1.0.0.
log  : Installing runtime.native.System.IO.Compression 4.1.0.
log  : Installing Microsoft.NETCore.DotNetHost 1.0.1.
log  : Installing NuGet.DependencyResolver.Core 3.5.0-beta2-1484.
log  : Installing Newtonsoft.Json 6.0.4.
log  : Installing NuGet.Packaging.Core 3.5.0-beta2-1484.
log  : Installing NuGet.Common 3.5.0-beta2-1484.
log  : Installing Microsoft.Extensions.DependencyModel 1.0.0.
log  : Installing Newtonsoft.Json 9.0.1.
log  : Installing NuGet.RuntimeModel 3.5.0-beta2-1484.
log  : Installing Microsoft.EntityFrameworkCore.Tools.DotNet 1.1.0-preview4-final.
log  : Installing Microsoft.DotNet.Cli.Utils 1.0.0-preview2-003121.
log  : Installing Microsoft.CSharp 4.0.1.
log  : Installing Microsoft.NETCore.DotNetHostPolicy 1.0.1.
log  : Installing Microsoft.NETCore.Runtime.CoreCLR 1.0.4.
log  : Installing System.Runtime.Serialization.Primitives 4.1.1.
log  : Installing Microsoft.VisualBasic 10.0.1.
log  : Installing System.ComponentModel 4.0.1.
log  : Installing NETStandard.Library 1.6.0.
log  : Installing System.Buffers 4.0.0.
log  : Installing System.ComponentModel.Annotations 4.1.0.
log  : Installing System.Collections.Immutable 1.2.0.
log  : Installing System.Diagnostics.DiagnosticSource 4.0.0.
log  : Installing System.Diagnostics.Process 4.1.0.
log  : Installing System.Dynamic.Runtime 4.0.11.
log  : Installing System.Globalization.Extensions 4.0.1.
log  : Installing System.IO.FileSystem.Watcher 4.0.0.
log  : Installing System.IO.MemoryMappedFiles 4.0.0.
log  : Installing System.IO.UnmanagedMemoryStream 4.0.1.
log  : Installing System.Linq.Expressions 4.1.0.
log  : Installing System.Linq.Parallel 4.0.1.
log  : Installing System.Linq.Queryable 4.0.1.
log  : Installing System.Net.NameResolution 4.0.0.
log  : Installing System.Net.Requests 4.0.11.
log  : Installing System.Net.Security 4.0.0.
log  : Installing System.Net.WebHeaderCollection 4.0.1.
log  : Installing System.Numerics.Vectors 4.1.1.
log  : Installing System.Reflection.DispatchProxy 4.0.1.
log  : Installing System.Reflection.Metadata 1.3.0.
log  : Installing System.Reflection.TypeExtensions 4.1.0.
log  : Installing System.Resources.Reader 4.0.0.
log  : Installing System.Runtime.Loader 4.0.0.
log  : Installing System.Security.Cryptography.Algorithms 4.2.0.
log  : Installing System.Security.Cryptography.Encoding 4.0.0.
log  : Installing System.Security.Cryptography.Primitives 4.0.0.
log  : Installing System.Security.Cryptography.Csp 4.0.0.
log  : Installing System.Security.Cryptography.X509Certificates 4.1.0.
log  : Installing System.Threading.Tasks.Dataflow 4.6.0.
log  : Installing System.Threading.Tasks.Extensions 4.0.0.
log  : Installing System.Threading.Tasks.Parallel 4.0.1.
log  : Installing System.Threading.Thread 4.0.0.
log  : Installing System.Threading.ThreadPool 4.0.10.
log  : Installing NuGet.Versioning 3.5.0-beta2-1484.
log  : Installing NuGet.Frameworks 3.5.0-beta2-1484.
log  : Installing Microsoft.DotNet.ProjectModel 1.0.0-rc3-003121.
log  : Installing NuGet.Packaging 3.5.0-beta2-1484.
log  : Installing NuGet.ProjectModel 3.5.0-beta2-1484.
log  : Installing System.ObjectModel 4.0.12.
log  : Installing System.Reflection.Extensions 4.0.1.
log  : Installing Microsoft.NETCore.DotNetHostResolver 1.0.1.
log  : Installing Microsoft.NETCore.Jit 1.0.4.
log  : Installing Microsoft.Win32.Primitives 4.0.1.
log  : Installing System.Globalization.Calendars 4.0.1.
log  : Installing System.IO.Compression 4.1.0.
log  : Installing System.IO.Compression.ZipFile 4.0.1.
log  : Installing System.Net.Http 4.1.0.
log  : Installing System.Net.Primitives 4.0.11.
log  : Installing System.Net.Sockets 4.1.0.
log  : Installing System.Runtime.InteropServices.RuntimeInformation 4.0.0.
log  : Installing System.Threading.Timer 4.0.1.
log  : Installing Microsoft.Win32.Registry 4.0.0.
log  : Installing runtime.native.System 4.0.0.
log  : Installing System.Reflection.Emit 4.0.1.
log  : Installing System.Reflection.Emit.ILGeneration 4.0.1.
log  : Installing System.Threading.Overlapped 4.0.1.
log  : Installing System.Reflection.Emit.Lightweight 4.0.1.
log  : Installing System.Security.Principal.Windows 4.0.0.
log  : Installing runtime.native.System.Net.Security 4.0.1.
log  : Installing runtime.native.System.Security.Cryptography 4.0.0.
log  : Installing System.Security.Claims 4.0.1.
log  : Installing System.Security.Cryptography.OpenSsl 4.0.0.
log  : Installing System.Security.Principal 4.0.1.
log  : Installing runtime.native.System.Net.Http 4.0.1.
log  : Installing System.Security.Cryptography.Cng 4.2.0.
log  : Restoring packages for tool 'Microsoft.DotNet.Watcher.Tools' in D:\NadekoBot\Nadeko\src\NadekoBot\project.json...
log  : Installing System.Runtime.CompilerServices.Unsafe 4.3.0.
log  : Installing Microsoft.Extensions.Primitives 1.1.0.
log  : Installing Microsoft.Extensions.Configuration.Abstractions 1.1.0.
log  : Installing Microsoft.Extensions.Logging.Abstractions 1.1.0.
log  : Installing Microsoft.Extensions.DependencyInjection.Abstractions 1.1.0.
log  : Installing Microsoft.Extensions.CommandLineUtils 1.1.0.
log  : Installing Microsoft.Extensions.Logging.Console 1.1.0.
log  : Installing Microsoft.Extensions.Logging 1.1.0.
log  : Installing Microsoft.DotNet.Watcher.Tools 1.1.0-preview4-final.
log  : Writing lock file to disk. Path: D:\NadekoBot\Nadeko\src\NadekoBot\project.lock.json
log  : D:\NadekoBot\Nadeko\src\NadekoBot\project.json
log  : Restore failed in 71698ms.

Errors in D:\NadekoBot\Nadeko\src\NadekoBot\project.json
    Unable to resolve 'Discord.Net.Commands (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.
    Unable to resolve 'Discord.Net.WebSocket (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.

D:\NadekoBot\Nadeko\src\NadekoBot>dotnet run --configuration Release
Project NadekoBot (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling NadekoBot for .NETCoreApp,Version=v1.0
D:\NadekoBot\Nadeko\src\NadekoBot\project.json(20,25): error NU1001: The dependency AngleSharp >= 0.9.9 could not be resolved.
D:\NadekoBot\Nadeko\src\NadekoBot\project.json(21,23): error NU1001: The dependency libvideo >= 1.0.1 could not be resolved.
D:\NadekoBot\Nadeko\src\NadekoBot\project.json(22,28): error NU1001: The dependency CoreCLR-NCalc >= 2.1.2 could not be resolved.
D:\NadekoBot\Nadeko\src\NadekoBot\project.json(23,47): error NU1001: The dependency Google.Apis.Urlshortener.v1 >= 1.19.0.138 could not be resolved.
D:\NadekoBot\Nadeko\src\NadekoBot\project.json(24,42): error NU1001: The dependency Google.Apis.YouTube.v3 >= 1.20.0.701 could not be resolved.
D:\NadekoBot\Nadeko\src\NadekoBot\project.json(25,47): error NU1001: The dependency Google.Apis.Customsearch.v1 >= 1.20.0.466 could not be resolved.
D:\NadekoBot\Nadeko\src\NadekoBot\project.json(26,38): error NU1001: The dependency ImageSharp >= 1.0.0-alpha4-00031 could not be resolved.
D:\NadekoBot\Nadeko\src\NadekoBot\project.json(27,46): error NU1001: The dependency ImageSharp.Drawing >= 1.0.0-alpha4-00031 could not be resolved.
D:\NadekoBot\Nadeko\src\NadekoBot\project.json(28,44): error NU1001: The dependency Microsoft.EntityFrameworkCore >= 1.1.0 could not be resolved.
D:\NadekoBot\Nadeko\src\NadekoBot\project.json(29,51): error NU1001: The dependency Microsoft.EntityFrameworkCore.Design >= 1.1.0 could not be resolved.
D:\NadekoBot\Nadeko\src\NadekoBot\project.json(30,51): error NU1001: The dependency Microsoft.EntityFrameworkCore.Sqlite >= 1.1.0 could not be resolved.
D:\NadekoBot\Nadeko\src\NadekoBot\project.json(31,49): error NU1001: The dependency Microsoft.Extensions.Configuration >= 1.1.0 could not be resolved.
D:\NadekoBot\Nadeko\src\NadekoBot\project.json(32,70): error NU1001: The dependency Microsoft.Extensions.Configuration.EnvironmentVariables >= 1.1.0 could not be resolved.
D:\NadekoBot\Nadeko\src\NadekoBot\project.json(33,54): error NU1001: The dependency Microsoft.Extensions.Configuration.Json >= 1.1.0 could not be resolved.
D:\NadekoBot\Nadeko\src\NadekoBot\project.json(34,55): error NU1001: The dependency Microsoft.Extensions.DependencyInjection >= 1.1.0 could not be resolved.
D:\NadekoBot\Nadeko\src\NadekoBot\project.json(36,56): error NU1001: The dependency Microsoft.Extensions.PlatformAbstractions >= 1.1.0 could not be resolved.
D:\NadekoBot\Nadeko\src\NadekoBot\project.json(41,36): error NU1001: The dependency Newtonsoft.Json >= 9.0.2-beta1 could not be resolved.
D:\NadekoBot\Nadeko\src\NadekoBot\project.json(42,26): error NU1001: The dependency NLog >= 5.0.0-beta03 could not be resolved.
D:\NadekoBot\Nadeko\src\NadekoBot\project.json(43,31): error NU1001: The dependency System.Xml.XPath >= 4.3.0 could not be resolved.
D:\NadekoBot\Nadeko\src\NadekoBot\project.json(37,30): error NU1001: The dependency System.Xml.XPath >= 4.3.0 could not be resolved.
D:\NadekoBot\Nadeko\src\NadekoBot\project.json(43,31): error NU1001: The dependency System.Xml.XPath >= 4.0.1 could not be resolved.
D:\NadekoBot\Nadeko\src\NadekoBot\project.json(37,30): error NU1001: The dependency System.Xml.XPath >= 4.0.1 could not be resolved.
D:\NadekoBot\Nadeko\src\NadekoBot\project.json(44,29): error NU1001: The dependency Discord.Net.Commands >= 1.0.0-* could not be resolved.
D:\NadekoBot\Nadeko\src\NadekoBot\project.json(48,30): error NU1001: The dependency Discord.Net.WebSocket >= 1.0.0-* could not be resolved.
D:\NadekoBot\Nadeko\src\NadekoBot\project.json(37,30): error NU1001: The dependency System.Collections.Immutable >= 1.2.0 could not be resolved.

Compilation failed.
    0 Warning(s)
    25 Error(s)

Time elapsed 00:00:00.0451645

------------------------------

Help me plssssss

**Comment by CharlieKek** [comment]
Everytime i try and run the .exe for the bot, it opens and closes in a split second, please help me.
